### ISSUE TITLE
Androd: Container background problem 

### ISSUE THREAD

**Issue by egemenokten** [WrathChaos/react-native-header-search-bar#2]
Container bottom looks too long in android 

![image](https://user-images.githubusercontent.com/30256104/69579763-371f9c00-0fe4-11ea-9320-83aa8b915b1d.png)

**Comment by fukemy** [comment]
why u close this issues?

**Comment by kuraydev** [comment]
Hey @fukemy 
Can you still reproduce this issue?

**Comment by fukemy** [comment]
it's my bad, default textinput were larger height in Android,  set heigh fixed this problem
